# SSH Tunnel Configuration for RDS PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/hrms
spring.datasource.username=hrmsadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# SSH Tunnel Configuration for ElastiCache Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AWS S3 Configuration for Recruitment Resumes
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.region=${AWS_REGION}

# AWS SES Configuration for Email Notifications
aws.ses.sender-email=${AWS_SES_SENDER_EMAIL}